apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  restartPolicy: Never

  containers:

  - name: nginx
    image: nkflyfly/nginx-abtesting:latest
    ports:
    - containerPort: 80

  - name: python-webserver-a
    image: nkflyfly/python-webserver:latest
    command: ["python"]
    args: ["/python-webserver.py", "8080", "Version_A"]

  - name: python-webserver-b
    image: nkflyfly/python-webserver:latest
    command: ["python"]
    args: ["/python-webserver.py", "8081", "Version_B"]

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    name: nginx-deployment
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
    nodePort: 30024
